[package]
name = "rust-coinselect"
version = "0.1.5"
edition = "2021"
description = "A blockchain-agnostic coin selection library built in Rust."
readme = "README.md"
documentation = "https://docs.rs/rust-coinselect"
keywords = ["UTXO", "coinselection", "subsetsum", "bitcoin", "blockchain"]
license = "MIT"
repository = "https://github.com/citadel-tech/rust-coinselect"

exclude = [".github"]

[dependencies]
rand = "0.8.5"

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
proptest = "1.7"
test-strategy = "0.4"

#Empty default feature set, (helpful to generalise in github actions)
[features]
default = []

[[bench]]
name = "benches"
harness = false

[[bench]]
name = "benches_srd"
harness = false

[[bench]]
name = "benches_bnb"
harness = false

[[bench]]
name = "benches_knapsack"
harness = false

[[bench]]
name = "benches_lowestlarger"
harness = false

[[bench]]
name = "benches_fifo"
harness = false

[[bench]]
name = "benches_leastchange"
harness = false

[profile.test]
opt-level = 3
